<a href="https://colab.research.google.com/github/Ramya1410/Python-Practice/blob/main/practice_simple_py_pgms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello')

hello


In [ ]:
n= int(input('enter a number: '))
if n < 0:
  print('Negative')
elif n==0:
  print('neither pos nor neg')
else:
  print('positive')


enter a number: -025
Negative


In [ ]:
n= int(input('enter a number: '))
if n%2==0:
  print('even')
else:
  print('odd')

enter a number: 52
even


In [ ]:
list1 = [int(x) for x in input('enter a range of numbers').split()]
res=[]
for i in list1:
  if i%2==0:
    pass
  else:
    res.append(i)
print(res)

enter a range of numbers11 25 45 66 35 22 88 99 47
[11, 25, 45, 35, 99, 47]


In [ ]:
word = input('enter a word: ')
rev =''.join(reversed(word))
print(rev)
if word == rev:
  print('palindrome')
else:
  print('not a palindrome')

enter a word: hello
olleh
not a palindrome


In [ ]:
n = int(input('enter a number'))
temp = n
rev = 0
while(n>0):
  dig = n%10
  rev = rev*10+dig
  n=n//10
if(temp == rev):
  print('pal')
else:
  print('not pal')

enter a number424
pal


In [ ]:
n = int(input('enter a number'))
rev=0
while(n>0):
  dig = n%10
  rev = rev*10+dig
  n=n//10
print(rev)

enter a number458
854


In [ ]:
lis=[]
for i in range(0,51):
  if(i%2!=0 and i%3!=0):
    lis.append(i)
  else:
    pass
print(lis)

[1, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49]


In [ ]:
lis=[]
for i in range(400,700):
  if(i%7==0 and i%5==0):
    lis.append(i)
  else:
    pass
print(lis)

[420, 455, 490, 525, 560, 595, 630, 665]


In [ ]:
lis=[]
n = int(input('enter a number'))
for i in range(0,51):
  if(i%n==0):
    lis.append(i)
  else:
    pass
print(lis)

enter a number6
[0, 6, 12, 18, 24, 30, 36, 42, 48]


In [ ]:
n = input('enter a number')
res=0
for i in n:
  res+=int(i)
print(res)

enter a number415
10


In [ ]:
n = int(input('enter a number'))
res=0
while(n>0):
  dig = n%10
  res+=dig
  n=n//10
print(res)

enter a number159
15


In [ ]:
n=input('enter a number: ')
l=[]
for i in n:
  l.append(i)
print(len(l))

enter a number: 789456123
9


In [ ]:
n= int(input('enter a no '))
count = 0
while(n>0):
  count+=1
  n=n//10
print(count)

enter a no 789456123
9


In [ ]:
n = int(input('enter a number'))
l=[]
for i in range(1,51):
  if n%i==0:
    l.append(i)
print(l)

enter a number500
[1, 2, 4, 5, 10, 20, 25, 50]


In [ ]:
n = int(input('enter a number'))
l=[]
for i in range(2,101):
  if n%i==0:
    l.append(i)
print(l)
print(min(l))

enter a number152
[2, 4, 8, 19, 38, 76]
2


In [ ]:
l=[]
def convert(n):
  if n==0:
    return l
  dig = n%2
  l.append(dig)
  convert(n//2)
a = int(input('enter a number'))
convert(a)
l.reverse()
for i in l:
  print(i,end='')

enter a number7
111

In [ ]:
n = int(input('enter a number'))
l=[]
while(n!=0):
  dig = n%2
  l.append(dig)
  n=n//2
l.reverse()
for i in l:
  print(i,end='')

enter a number7
111

In [ ]:
n = int(input('enter a number'))
for i in range(1,11):
  print(i*n)


enter a number11
11
22
33
44
55
66
77
88
99
110


In [ ]:
n = int(input('enter marks of the student'))
if n<=100 and n>=85:
  print('A Grade')
elif n<85 and n>=70:
  print('B Grade')
elif n<70 and n>=55:
  print('C Grade')
elif n<55 and n>=35:
  print('D Grade')
else:
  print('FAIL')

enter marks of the student88
A Grade


In [ ]:
n = int(input('enter year'))
if n%4==0 and n%100!=0 or n%400==0:
  print('Leap year')
else:
  print('not leap year')

enter year2016
Leap year


In [ ]:
n = float(input('enter the value in cms'))
inch = n/2.5
print('its equivalent in inches is: ',inch)
foot = inch /12
print('its equivalent in feet is: ',foot)


enter the value in cms170
its equivalent in inches is:  68.0
its equivalent in feet is:  5.666666666666667


In [ ]:
n = input('enter a number')
res=0
for i in range(1,11):
  res+=int(n*i)
print(res)

enter a number2
2469135800


In [ ]:
date = input('enter date')
dd,mm,yy = date.split('/')
dd=int(dd)
mm=int(mm)
yy=int(yy)
if(mm==1 or mm==3 or mm==5 or mm==7 or mm==8 or mm==10 or mm==12):
  max = 31
elif(mm==4 or mm==6 or mm==9 or mm==11):
  max = 30
elif(yy%4==0 and yy%100!=0 or yy%400==0):
  max = 29
else:
  max = 28
if(dd==max and mm!=12):
  dd=1
  mm=mm+1
  print('the incremented date is: ',dd,mm,yy)
elif(dd==max and mm==12):
  dd=1
  mm=1
  yy=yy+1
  print('the incremented date is ',dd,mm,yy)
else:
  dd+=1
  print('the incremented date is ',dd,mm,yy)

enter date31/12/2016
the incremented date is  1 1 2017


In [ ]:
import numpy as np
a = [int(x) for x in input('enter numbers for list 1').split()]
b = [int(x) for x in input('enter numbers for list 2').split()]
print(a,b)
arr1= np.array(a).reshape(3,3)
print(arr1)
arr2=np.array(b).reshape(3,3)
print(arr2)
res = arr1+arr2
print(res)


enter numbers for list 11 2 1 2 1 2 1 2 1
enter numbers for list 22 1 2 1 2 1 2 1 2
[1, 2, 1, 2, 1, 2, 1, 2, 1] [2, 1, 2, 1, 2, 1, 2, 1, 2]
[[1 2 1]
 [2 1 2]
 [1 2 1]]
[[2 1 2]
 [1 2 1]
 [2 1 2]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
print(np.__version__)

1.21.6


In [ ]:
a = np.array([[1,2,3],[3,2,1]])
b = np.array([[1,2,4],[4,2,1]])
c=a+b
print(c)

[[2 4 7]
 [7 4 2]]


In [ ]:
a = [int(x) for x in input('enter numbers for list 1').split()]
b = [int(x) for x in input('enter numbers for list 2').split()]
print(a,b)
arr1= np.array(a).reshape(3,3)
print(arr1)
arr2=np.array(b).reshape(3,3)
print(arr2)
arr1 = arr1*2
arr2 = arr2*2
print(arr1,arr2,end='\n')

enter numbers for list 11 2 1 2 1 2 1 2 1
enter numbers for list 22 1 2 1 2 1 2 1 2
[1, 2, 1, 2, 1, 2, 1, 2, 1] [2, 1, 2, 1, 2, 1, 2, 1, 2]
[[1 2 1]
 [2 1 2]
 [1 2 1]]
[[2 1 2]
 [1 2 1]
 [2 1 2]]
[[2 4 2]
 [4 2 4]
 [2 4 2]] [[4 2 4]
 [2 4 2]
 [4 2 4]]


In [ ]:
a = [[int(y) for y in x] for x in input('enter numbers for list 1').split()]
b = [[int(y) for y in x] for x in input('enter numbers for list 2').split()]
arr1 = np.array(a).reshape(3,3)
arr2 = np.array(b).reshape(3,3)
res = np.hstack((arr1,arr2))
print(res)


enter numbers for list 1[1,2,3]    [4,5,6]


ValueError: ignored

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.vstack((a1, a2))

print(o)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
