<a href="https://colab.research.google.com/github/Ramya1410/Python-Practice/blob/main/py_pgms_on_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ul= int(input('enter upper limit'))
for a in range(2,ul+1):
  k=0
  for i in range(2,a//2+1):
    if(a%i==0):
      k=k+1
  if(k<=0):
    print(a)


enter upper limit20
2
3
5
7
11
13
17
19


In [ ]:
n = int(input('enter a number'))
k=0
for i in range(2,n//2+1):
  if(n%i==0):
    k=k+1
if(k<=0):
  print('prime')
else:
  print('not prime')


enter a number47
prime


In [ ]:
def isprime(n,div=None):
  if div == None:
    div = n-1
  while(div>=2):
    if(n%div==0):
        print('not prime')
        return False
    else:
        return isprime(n, div-1)
  else:
      print('prime')
      return True
a = int(input('enter a no '))
isprime(a)

enter a no 54
not prime


False

In [ ]:
n = int(input('enter a number'))
l=[]
for i in range(1,n//2+1):
  if(n%i==0):
    l.append(i)
print(l)
if sum(l)==n:
  print('perfect number')
else:
  print('no')

enter a number496
[1, 2, 4, 8, 16, 31, 62, 124, 248]
perfect number


In [ ]:
n= input('enter a number ')
sum=0
for i in n:
  i = int(i)
  sum=sum+i**3
if sum == n:
  print('yes')
else:
  print('no')

enter a number371
27
no


In [ ]:
n = int(input('enter a number'))
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

enter a number18
171


In [ ]:
n = int(input('enter a number'))
sum=0 
temp = n
while(n):
  i=1
  f=1
  r=n%10
  while(i<=r):
    f=f*i
    i=i+1
  sum=sum+f
  n=n//10
if(sum==temp):
  print('strong')
else:
  print('not strong')


enter a number145
strong


In [ ]:
def printno(upper):
    if(upper>0):
        printno(upper-1)
        print(upper)
upper=int(input("Enter upper limit: "))
printno(upper)

Enter upper limit: 14
1
2
3
4
5
6
7
8
9
10
11
12
13
14


numpy 10 - 20 basics


In [ ]:
import numpy as np
l1 = [int(x) for x in input('enter numbers').split()]
arr = np.array(l1)
print(arr)
arr = arr.astype(float)
print(arr)

enter numbers1 2 4 5 6 7 8 9
[1 2 4 5 6 7 8 9]
[1. 2. 4. 5. 6. 7. 8. 9.]


In [ ]:
l1 = np.arange(0,101,4)
print(l1)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100]


In [ ]:
l1 = [int(x) for x in input('enter numbers').split()]
l2 = [int(x) for x in input('enter numbers').split()]
arr1 = np.array(l1)
arr2 = np.array(l2)
print(arr1)
print(arr2)
print(np.where(arr1==arr2))


enter numbers1 2 3 5 4
enter numbers2 1 3 5 4
[1 2 3 5 4]
[2 1 3 5 4]
(array([2, 3, 4]),)


In [ ]:
n = np.linspace(0,100,6)
print(n)

[  0.  20.  40.  60.  80. 100.]


In [ ]:
n = np.full((3,3),5)
print(n)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
a = np.ones((3,4))
a*3
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
o = np.tile(a,5)
print(o)

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [ ]:
np.random.seed(123)
a = np.random.randint(0,16,size = (5,4))
print(a)

[[14 13 14  2]
 [12  2  6  1]
 [ 3 10 11  9]
 [ 6  1  0  1]
 [14 15  9  0]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrt = arr.T
print(arrt)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
n = int(input('enter a number '))
l=[]
for i in range(1,n+1):
  if(n%i==0):
    l.append(i)
print(l)
l1=[]
for a in l:
  for b in range(2,max(l)):
    if(a%b!=0):
      l1.append(a)
print(l1)

enter a number 20
[1, 2, 4, 5, 10, 20]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]


In [ ]:
n1 = int(input('enter a number '))
n2 = int(input('enter a number '))
l1=[]
l2=[]
for i in range(1,n1//2+1):
  if(n1%i==0):
    l1.append(i)
for i in range(1,n2//2+1):
  if(n2%i==0):
    l2.append(i)
if(sum(l1)==n2) and (sum(l2)==n1):
  print('amicable')
else:
  print('not')



enter a number 220
enter a number 284
amicable


In [ ]:
n = int(input('enter a number '))
count = 0
k=0
while(n>1):
  if(n%2==0):
    count+=1
    n=n//2
  else:
    n=1
    k=1   
if(count>0) and (k!=1):
  print('yes, power of two. Power: ',count)
elif(count<0) or (k==1):
  print('not')

enter a number 20
not


In [ ]:
n = int(input('enter a number for base '))
m = int(input('enter exp value'))
pow = n**m
print(pow)


enter a number for base 5
enter exp value3
125


In [ ]:
def product(a,b):
  if(a<b):
    return product(b,a)
  elif(b!=0):
    return (a+product(a,b-1))
  else:
    return 0
a = int(input('enter a number '))
b = int(input('enter a number '))
product(a,b)


enter a number 10
enter a number 12


120

In [ ]:
ll = int(input('enter lower limit'))
ul = int(input('enter upper limit'))
n = [x for x in range(ll,ul+1) if(int(x**0.5))**2==x and sum(list(map(int,str(x))))<10]
print(n)

enter lower limit1
enter upper limit40
[1, 4, 9, 16, 25, 36]


In [ ]:
a = int(input('enter a number 1 '))
b = int(input('enter a number 2 '))
c = int(input('enter a number 3 '))
d=[]
d.append(a)
d.append(b)
d.append(c)
for i in range(0,3):
  for j in range(0,3):
    for k in range(0,3):
      if((i!=j)&(j!=k)&(k!=i)):
        print(d[i],d[j],d[k])


enter a number 1 4 
enter a number 2 5
enter a number 3 6
4 5 6
4 6 5
5 4 6
5 6 4
6 4 5
6 5 4
